# --- Required options --- #

# Name of website
title: Data compression and compressed data structures

description: Computer Science Dept. University of Pisa 

show_downloads: false


theme: jekyll-theme-cayman
