# --- Required options --- #

# Name of website
title: PhD Course: Data compression and compressed data structures

description: Computer Science Dept. University of Pisa 

theme: jekyll-theme-cayman
