# --- Required options --- #

# Name of website
title: Data compression and compressed data structures

description: Computer Science Dept. University of Pisa 


# Your name to show in the footer
author: Some Person

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"


theme: jekyll-theme-cayman
