# --- Required options --- #

# Name of website
title: PhD Course: Data compression and compressed data structures

# Your name to show in the footer
author: Giovanni Manzini

theme: jekyll-theme-cayman
