
# Name of website
title: Data compression and compressed data structures

description: A course on data compression and compressed data structures from the University of Pisa 

show_downloads: false


theme: jekyll-theme-cayman
